version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "127.0.0.1:6001:5000"
    links:
    - mymongo
    restart: unless-stopped
    hostname: pydigger-web
    volumes:
      - logs:/logs

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    links:
    - mymongo
    restart: unless-stopped
    entrypoint: cron -f -L3
    hostname: pydigger-cron
    volumes:
      - logs:/logs

  mymongo:
    build:
      context: mongodb
      dockerfile: Dockerfile
    mem_limit: 4096m
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
      - ./backup:/backup
      - ./tools:/tools
    restart: unless-stopped
    hostname: pydigger-mongodb

volumes:
  mongo-data:
  mongo-configdb:
  logs:
